version: '3'
services:
  riffraff-db:
    container_name: riffraff-db
    image: postgres:10.6
    ports:
    - 7432:5432
    environment:
    - POSTGRES_USER=riffraff
    - POSTGRES_PASSWORD=riffraff
    - POSTGRES_DB=riffraff
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
