name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: build + test
        run: |
          set -e
          # Ensure we don't overwrite existing (Teamcity) builds.
          # LAST_TEAMCITY_BUILD=TODO
          # export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          sbt clean compile riffraff/riffRaffUpload
